### ISSUE TITLE
Signidice algorithm

### ISSUE THREAD

**Issue by EvgenRad81** [airalab/dao.casino#1]
необходимо имплементировать вот этот протокол https://github.com/Matchpool/contracts/blob/master/contracts/Contribution.sol 

Вкратце, что я понял:
1)игрок отправляет seed
2) держатель банкрола (не контракт) забирает seed из контракта
3) подписывает ее закрытым ключем (я проверил метод в JS ethUtil.ecsign из EthereumJS) и отправляет эту подпись обратно в контракт (и дополнительные данные r,s,v для валидации подписи)
4) контракт проверяет, что хеш прислал именно держателем банкрола, и что подписан именно seed клиента через функцию ecrecover 
5) собно полученный хеш пропускаем через uint(hash)%maxnum;  и получается число от 0 до maxnum. 

пример https://gist.github.com/noxonsu/82eff25bf0c537dce1a331b0b8863137

**Comment by akru** [comment]
1. https://github.com/Matchpool/contracts/blob/master/contracts/Contribution.sol - это контракт краудсейла, что из него нужно имплементировать?
2. Зачем эти игры с подписью, банкролл и так подписывает транзакцию при отправке, можно просто смотреть на `msg.sender`.

**Comment by noxonsu** [comment]
я извиняюсь не то вставил, вот протокол https://github.com/gluk256/misc/blob/master/rng4ethereum/signidice.md

**Comment by noxonsu** [comment]
Проверил контракт, подключив его к фронтенду и после незначительных изменений, удалось запустить игру, а со стороны кзаино получить лог с юзерским хешем (V), подписать его, отправить cofirm, пройти проверку валидности и передать рандомное число для дальнейшей обработки в игре. 

Мои предложения:

1. V конкатенацию хранить в bytes32, а не uint256 (с uint256 не получилось у меня справится)
2. сохранять V сразу в структуру игры и брать его оттуда при конфирме, так как он не меняется, подписант оттудаже возьмет
3. инфура (пока) не отдает логи из pending транзакций (просто зависает запрос), нужно сделать, чтоб овнер мог дернуть новую игру через eth_Call, думаю нужен метод который отдаст счетчик игр
4. в confirm добавить проверку, чтоб подписант два раза случайно не прислал результат
5. написать тесты на truffle (если это задержит, то отложим)
6. рассмотреть все таки вариант удалять отработаные игры, чтоб не захломлять блокчейн
7. в event с директивой indexed есть небольшой глюк, например ремикс выдает всегда 0
8. не давать прислать пустой или слишком маленький рандом
9. 

дальнейшие действия:
нужно обеспечить заменяемость генератора рандома (он же банкрол) в задеплоеном контракте игры. 
Например мы сделаем setBankRollContract(address) в играх, нужно подумать кто сможет эту фунецию вызывать, овнер игры или через дао как то.

**Comment by akru** [comment]
1. V - производная от имеющихся данных, хранить ее не имеет смысла `чтоб не захломлять`;
2. //-//-//
3. не понял, прошу подробнее
4. можно кидать исключение при повторном приходе транзакции с тем же `_id`;
5. пока отложим, прошу сделать отдельный issue
6. удалять лучше контракт целиком, менеджмент отработанных игр усложнит логику работы и создаст благоприятную почву для ошибок и уязвимостей, это экономия на спичках;
7. аргументы `indexed` присутствую как раз `чтоб не захломлять`;
8. Какая проблема с маленьким или пустым полем `_random`?

Новый банкролл - новый контракт, просто и надежно.

**Comment by noxonsu** [comment]
1,2 проще для отладки, слишком много операций на фронте нужно делать, 
3 в текущей версии мы будем ждать пока замайнится транзакция с V, потом через eth_getLogs фронтенд банкрола может получить данные которые надо подписывать, согласно протоколу можно ускорить этот процесс, например попросив ноду отдать логи из транзакций которые pending, у меня не получилось получить эти логи, но у нас точно работает eth_Call с параметром pending, нужно добавить function getTotalGames {return games.length; } тогда с фронта можно следить, что счетчик увеличился и дернуть V  и сразу загружать результат не дожидаясь майнинга первой транзакции

остальное ок, по п 8 просто параноя.

**Comment by noxonsu** [comment]
по 3 пока отложим до следующей недели, пока что остается только V перевести в bytes32 и хранить в структуре, для удобства работы на фронтенде. с остальным согласен

**Comment by akru** [comment]
Внес исправления в https://github.com/airalab/dao.casino/commit/f7a87f62bb05c7f97f6331a56cd35d8492d73d82
